# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc7f79c1ed6ddb971c25b89851626b78fbe1efe36eaa3e2690e7ccba67c093680ec34f4a4eed5f4523de1aa22155947db5f8069655c792bf6ce742f785248ede

test:
  secret_key_base: 8b88513cd8ef1f4e97ccab5f5014607376362d45746c6e01d20836a0690ea2e3516165665a85d0f409d2d1c9e151aaa7b39dded5dcfe3396191dbd3e9c647c4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
