country = Country.find_by(name: 'United States')

State.create!([
                  {name: 'Michigan', abbr: 'MI', country: country},
                  {name: 'South Dakota', abbr: 'SD', country: country},
                  {name: 'Washington', abbr: 'WA', country: country},
                  {name: 'Wisconsin', abbr: 'WI', country: country},
                  {name: 'Arizona', abbr: 'AZ', country: country},
                  {name: 'Illinois', abbr: 'IL', country: country},
                  {name: 'New Hampshire', abbr: 'NH', country: country},
                  {name: 'North Carolina', abbr: 'NC', country: country},
                  {name: 'Kansas', abbr: 'KS', country: country},
                  {name: 'Missouri', abbr: 'MO', country: country},
                  {name: 'Arkansas', abbr: 'AR', country: country},
                  {name: 'Nevada', abbr: 'NV', country: country},
                  {name: 'District of Columbia', abbr: 'DC', country: country},
                  {name: 'Idaho', abbr: 'ID', country: country},
                  {name: 'Nebraska', abbr: 'NE', country: country},
                  {name: 'Pennsylvania', abbr: 'PA', country: country},
                  {name: 'Hawaii', abbr: 'HI', country: country},
                  {name: 'Utah', abbr: 'UT', country: country},
                  {name: 'Vermont', abbr: 'VT', country: country},
                  {name: 'Delaware', abbr: 'DE', country: country},
                  {name: 'Rhode Island', abbr: 'RI', country: country},
                  {name: 'Oklahoma', abbr: 'OK', country: country},
                  {name: 'Louisiana', abbr: 'LA', country: country},
                  {name: 'Montana', abbr: 'MT', country: country},
                  {name: 'Tennessee', abbr: 'TN', country: country},
                  {name: 'Maryland', abbr: 'MD', country: country},
                  {name: 'Florida', abbr: 'FL', country: country},
                  {name: 'Virginia', abbr: 'VA', country: country},
                  {name: 'Minnesota', abbr: 'MN', country: country},
                  {name: 'New Jersey', abbr: 'NJ', country: country},
                  {name: 'Ohio', abbr: 'OH', country: country},
                  {name: 'California', abbr: 'CA', country: country},
                  {name: 'North Dakota', abbr: 'ND', country: country},
                  {name: 'Maine', abbr: 'ME', country: country},
                  {name: 'Indiana', abbr: 'IN', country: country},
                  {name: 'Texas', abbr: 'TX', country: country},
                  {name: 'Oregon', abbr: 'OR', country: country},
                  {name: 'Wyoming', abbr: 'WY', country: country},
                  {name: 'Alabama', abbr: 'AL', country: country},
                  {name: 'Iowa', abbr: 'IA', country: country},
                  {name: 'Mississippi', abbr: 'MS', country: country},
                  {name: 'Kentucky', abbr: 'KY', country: country},
                  {name: 'New Mexico', abbr: 'NM', country: country},
                  {name: 'Georgia', abbr: 'GA', country: country},
                  {name: 'Colorado', abbr: 'CO', country: country},
                  {name: 'Massachusetts', abbr: 'MA', country: country},
                  {name: 'Connecticut', abbr: 'CT', country: country},
                  {name: 'New York', abbr: 'NY', country: country},
                  {name: 'South Carolina', abbr: 'SC', country: country},
                  {name: 'Alaska', abbr: 'AK', country: country},
                  {name: 'West Virginia', abbr: 'WV', country: country},
                  {name: 'U.S. Armed Forces - Americas', abbr: 'AA', country: country},
                  {name: 'U.S. Armed Forces - Europe', abbr: 'AE', country: country},
                  {name: 'U.S. Armed Forces - Pacific', abbr: 'AP', country: country}
              ])

country = Country.find_by(name: '中国')

State.create!([
                  {name: '北京', abbr: 'BJ', country: country},
                  {name: '天津', abbr: 'TJ', country: country},
                  {name: '河北', abbr: 'HE', country: country},
                  {name: '山西', abbr: 'SX', country: country},
                  {name: '内蒙古自治区', abbr: 'NM', country: country},
                  {name: '辽宁', abbr: 'LN', country: country},
                  {name: '吉林', abbr: 'JL', country: country},
                  {name: '黑龙江', abbr: 'HL', country: country},
                  {name: '上海', abbr: 'SH', country: country},
                  {name: '江苏', abbr: 'JS', country: country},
                  {name: '浙江', abbr: 'ZJ', country: country},
                  {name: '安徽', abbr: 'AH', country: country},
                  {name: '福建', abbr: 'FJ', country: country},
                  {name: '江西', abbr: 'JX', country: country},
                  {name: '山东', abbr: 'SD', country: country},
                  {name: '河南', abbr: 'HN', country: country},
                  {name: '湖北', abbr: 'HB', country: country},
                  {name: '湖南', abbr: 'HN', country: country},
                  {name: '广东', abbr: 'GD', country: country},
                  {name: '广西壮族自治区', abbr: 'GX', country: country},
                  {name: '海南', abbr: 'HI', country: country},
                  {name: '重庆', abbr: 'CQ', country: country},
                  {name: '四川', abbr: 'SC', country: country},
                  {name: '贵州', abbr: 'GZ', country: country},
                  {name: '云南', abbr: 'YN', country: country},
                  {name: '西藏自治区', abbr: 'XZ', country: country},
                  {name: '陕西', abbr: 'SN', country: country},
                  {name: '甘肃', abbr: 'GS', country: country},
                  {name: '青海', abbr: 'QH', country: country},
                  {name: '宁夏回族自治区', abbr: 'NX', country: country},
                  {name: '新疆维吾尔自治区', abbr: 'XJ', country: country},
                  {name: '香港特别行政区', abbr: 'HK', country: country},
                  {name: '澳门特别行政区', abbr: 'MO', country: country},
                  {name: '台湾', abbr: 'TW', country: country}
              ])
